---
# tasks file for adopt-open-jdk
- include_tasks: variables.yml

- include_tasks: setup-OS-Family-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-OS-Family-RedHat.yml
  when: ansible_os_family == 'RedHat'
